"""Add encryption fields to users table

Revision ID: 9b7906fd7307
Revises: 
Create Date: 2025-09-08 21:07:20.757349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7906fd7307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('encrypted_dek', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('encryption_salt', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('key_verification_payload', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('encryption_method', sa.String(length=50), nullable=False, server_default='PBKDF2-SHA256'))
    op.add_column('users', sa.Column('key_derivation_iterations', sa.Integer(), nullable=False, server_default='500000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key_derivation_iterations')
    op.drop_column('users', 'encryption_method')
    op.drop_column('users', 'key_verification_payload')
    op.drop_column('users', 'encryption_salt')
    op.drop_column('documents', 'encrypted_dek')
    # ### end Alembic commands ###
